### ISSUE TITLE
Akira GIFS

### ISSUE THREAD

**Issue by Pomilui** [Pomilui/Akira_Page#18]
@quantum-satire 

Hey, Ally.  Here's the link to the movie, decent quality:  http://watchcartoonsonline.be/watch-akira-1988-full-movie-english-dub/

  1st bike GIF:  6:49 - 6:57

2nd   Tetsuo vs laser squad:  1:24:54 - 1:25:00

3rd   Ending; Universe disappears in Kaneda's hand:  1:58:36  -  1:58:52.  

4th  Tetsuo vs Kaneda:  1:04:55 - 1:05:05  

5th  Akira's Return:  1:49:45 - 1:50:00

@quantum-satire 
Update:  Here are some others that I may add:  
1:  https://giphy.com/gifs/akira-gif-NC1ifXeg9myiY
2:  https://giphy.com/gifs/akira-LLqaAwJCrmwoM
3:  https://tenor.com/view/akira-dream-nightmare-sleep-gif-8850911
4:  https://giphy.com/gifs/akira-favorite-films-Eu1zH3cr3a6Ri

This last one is for fun.  It shows how influential Akira has been to other anime:  https://soranews24.com/2016/08/08/amazing-gif-compiles-some-of-the-best-times-people-borrowed-this-scene-from-akira/

**Comment by quantum-satire** [comment]
@Pomilui @MarkTheShark01 How do these look? The quality did not transfer well and many of them are different sizes because of the difficulty scaling them and keeping the quality. 
![akira-1](https://user-images.githubusercontent.com/28074589/38712216-2ba78b18-3e98-11e8-99e3-444aa3d39346.gif)
![akira-2](https://user-images.githubusercontent.com/28074589/38712217-2c07aa34-3e98-11e8-85ad-8e47255726b5.gif)
![akira-3](https://user-images.githubusercontent.com/28074589/38712222-32685ac2-3e98-11e8-8b99-acab1b59eac6.gif)
![akira-4](https://user-images.githubusercontent.com/28074589/38712223-32791fce-3e98-11e8-991b-d1d509b03001.gif)
![akira-5](https://user-images.githubusercontent.com/28074589/38712224-328b90b4-3e98-11e8-93bd-3a6979904f5d.gif)

**Comment by Pomilui** [comment]
Excellent!  I know just where to put these in the script.  Thanks, Ally (sp).

**Comment by quantum-satire** [comment]
@Pomilui No problem! I pushed them to the repo in the images folder :)

**Comment by Pomilui** [comment]
@quantum-satire @MarkTheShark01 

   Adding them and the character photos to the newfire images folder.
